### ISSUE TITLE
Lägg till länk till samboendeavtal

### ISSUE THREAD

**Issue by Herkarl** [datasektionen/styrdokument#198]
För närvarande så länkas samboavtalet endast på [datasektionen.se/organisation](https://datasektionen.se/organisation#styrdokument) (under titeln styrdokument). Varje gång jag ska leta efter samboavtalet så är min första tanke att kolla i styrdokument, så jag tycker att det borde länkas någonstans här. Denna åsikt anser jag stärkas av att det ligger under rubriken styrdokument på den sida där de finns på just nu.

**Comment by Herkarl** [comment]
Skulle snyggast fixas genom att lägga till en länk till [pdf:en](https://static.datasektionen.se/organisation/samboendeavtal2021) i den vänstra sidebaren. Detta skulle dock kräva att den läggs till i [styrdokument-bawang](https://github.com/datasektionen/styrdokument-bawang) snarare än i det här repot, vilket är oönskvärt eftersom processen för att uppdatera samboavtalet då inte blir samma som för resterande styrdokument.

Andra lösningar:
- Lägga till en länk typ på huvudsidan
  + (+) Väldigt simpelt att fixa
  + (-) Ger intrycket att samboavtalet har högre status än tex stadgar?
  + (-) Ostandard och fult
- Bygga om styrdokument-bawang lit
  + (+) Roligare, och jag hade tänkt sätta mig in i det för att fixa en annan grej med högersidbaren ändå
  + (+) Blir mycket snyggare
  + (-) Jobbigare
  + (-) Behöver komma på ett snyggt sätt att implementera som också är intuitivt

**Comment by Herkarl** [comment]
Åsikter? @datasektionen/d-rektoratet @datasektionen/dev

**Comment by niklasvatn** [comment]
Har inte kollat på styrdokument-bawang tidigare, men antar att det det kan vara ett litet roligt projekt.
Det har också snackats om att lägga till engelska styrdokument också så det kanske kan fixas samtidigt?

**Comment by Herkarl** [comment]
> Det har också snackats om att lägga till engelska styrdokument också så det kanske kan fixas samtidigt?

Matteus har tydligen redan lagt till den översatta versionen av styrdokumenten (färdigt?) i en [branch](https://github.com/datasektionen/styrdokument/tree/english-documents) i det här repot, så det vore nog ganska simpelt att fixa.

**Comment by psoder** [comment]
Fixat i #246
