### ISSUE TITLE
Fixa referenser i styrdokumententen

### ISSUE THREAD

**Issue by Plongy** [datasektionen/styrdokument#84]

**Comment by augustjanse** [comment]
Var ligger den funktionen? Eller var borde den ligga?

**Comment by Plongy** [comment]
Alltså, man refererar lite till höger och vänster med paragrafnumreringen. Så det borde lösas på något sätt, antingen att man hittar något smart sätt att göra det på eller att man går igenom dokumenten manuellt och reder ut referenserna och skriver dem i klartext

**Comment by augustjanse** [comment]
Men finns det planer för att hantera referenserna i typ Taitan eller nåt? Vem har koll? Det tar ju inte lång tid att göra om det till vanliga Markdown-länkar, bara ingen har andra planer för referenserna.

**Comment by augustjanse** [comment]
Gjorde så stadgarna använder Markdown-länkar av typen:

    ... enligt §[2.2] ...
    
    ...
    
    [2.2]: #2-2-hedersmedlem
