### ISSUE TITLE
Fixa paragrafnumrering i styrdokumenten

### ISSUE THREAD

**Issue by Plongy** [datasektionen/styrdokument#85]

**Comment by augustjanse** [comment]
§5.1.4.5.1 refererar en paragraf i (det onumrerade) reglementet, så eventuellt borde man länka dit i samband med att man numrerar reglementet (som del av #84).

**Comment by augustjanse** [comment]
IMO borde också de kortare dokumenten numreras. Förslagsvis med mitt skript [paragraf](https://github.com/augustjanse/paragraf)! Jag fixar senare om ni inte har nåt emot det.
