### ISSUE TITLE
Fixa konsekvent versalisering av titlar och nämndnamn

### ISSUE THREAD

**Issue by cervyvin** [datasektionen/styrdokument#91]

**Comment by augustjanse** [comment]
Se min kommentar #90!

**Comment by luminiusa** [comment]
Tycker personligen att man borde ha gemener för [titlar](https://sv.wikipedia.org/wiki/Versalisering#Jobbtitlar_och_befattningar).

**Comment by Plongy** [comment]
Man bör ha gemener för titlar, det är skrivregeln på svenska

**Comment by augustjanse** [comment]
Jag håller med, men det är inte riktigt så enkelt. I princip skulle ett egennamn också kunna vara en titel, t.ex. Konglig Öfverdrif. Jag skulle vilja sätta gemener på alltihopa, men jag kan tänka mig att vissa nämnder kan vilja hålla kvar vid sin traditionella versalisering (typ Mottagningen). Därför tänker jag att en motion kan vara lämpligt för att ändra på det.

En del nämnder kan tolkas som antingen namn eller beskrivningar ("programmets studienämnd"/"Studienämnden"), så där finns det inte heller något självklart svar.

Vill också anmärka på att versaliseringen redan är _konsekvent_, även om den inte enligt svenska skrivregler är _korrekt_.

(Om man börjar från början så är själva sektionens namn Konglig Datasektionen en otypisk versalisering. Detta i likhet med "Kungliga" som enligt vissa regler följs av en versal.

> ... då ett namn föregås av Kungliga behåller man stor begynnelsebokstav på egennamnet ...

Det leder dock till att Konglig Öfverdrif och Lokalchef följer samma mönster. De är dock inte egennamn och skulle kunna skrivas som gemener.)

**Comment by augustjanse** [comment]
>En del nämnder kan tolkas som antingen namn eller beskrivningar ("programmets studienämnd"/"Studienämnden"), så där finns det inte heller något självklart svar.

https://twitter.com/Sprakradgivning/status/912576687761760256 😉

Vill ni att det här ska upprätthållas får ni gärna tänka på det när ni mergar ändringar förresten.
